// SPDX-License-Identifier: MIT
pragma solidity 0.8.29;

string constant DESCRIPTION = "# [RFC] Update Crosschain Governance Parameters for Avalanche, MegaETH, Soneium, and X Layer\n"
  "\n" "## Summary\n" "\n"
  "Secure crosschain messaging is an integral part of Uniswap's governance model. Governance votes like protocol fee adjustments are executed by UNI holders on Ethereum Mainnet and must subsequently be relayed to destination chains.\n"
  "\n" "\n" "\n"
  "This proposal updates Uniswap's crosschain governance system to accommodate the latest best practices. Specifically, we propose to:\n"
  "\n" "\n" "\n"
  "* Transition ownership of the Uniswap v2 and v4 contracts on Soneium and X Layer to CrossChainAccount contracts, which we consider to be the current best practice for executing messages from Ethereum Mainnet on the OP Stack\n"
  "\n"
  "* Migrate the entire messaging system for the Avalanche and MegaETH deployments from LayerZero v1 (part of which is [being deprecated](https://layerzero.network/blog/ongoing-security-updates)) to Wormhole \n"
  "\n" "\n" "\n"
  "Note that because Uniswap v3 on both Soneium and X Layer is owned by the `v3OpenFeeAdapter`, which is owned by the CrossChainAccount, we do not need to change the parameter on v3 on these chains.\n"
  "\n" "\n" "\n" "---\n" "\n" "## Specification\n" "\n"
  "### Current Configuration - Avalanche and MegaETH\n" "\n"
  "Both chains currently use LayerZero v1 for governance messaging:\n" "\n"
  "| Contract | Chain | Address |\n" "| :---- | :---- | :---- |\n"
  "| OmnichainProposalSender | Ethereum | [0xeb0BCF27D1Fb4b25e708fBB815c421Aeb51eA9fc](https://etherscan.io/address/0xeb0BCF27D1Fb4b25e708fBB815c421Aeb51eA9fc) |\n"
  "| OmnichainGovernanceExecutor | Avalanche | [0xeb0BCF27D1Fb4b25e708fBB815c421Aeb51eA9fc](https://snowtrace.io/address/0xeb0BCF27D1Fb4b25e708fBB815c421Aeb51eA9fc) |\n"
  "| OmnichainGovernanceExecutor | MegaETH | [0x8819b86ddF592c3aaAa6f9ec7cE1A0f99FC4322c](https://explorer.megaeth.com/address/0x8819b86ddF592c3aaAa6f9ec7cE1A0f99FC4322c) |\n"
  "\n" "### Proposed Configuration - Avalanche and MegaETH\n" "\n"
  "The LayerZero contracts are replaced with the Wormhole bridge infrastructure from [uniswapfoundation/Uniswap-Wormhole-Bridge](https://github.com/uniswapfoundation/Uniswap-Wormhole-Bridge):\n"
  "\n"
  "**UniswapWormholeSender (Ethereum):** The existing sender contract already deployed on mainnet will be reused - no new deployment required. \n"
  "\n"
  "**UniswapWormholeReceiver (Avalanche and MegaETH):** Uniswap Labs has deployed new UniswapWormholeReceiver contracts on both chains. This proposal will authorize them as the trusted governance executors for each chain.\n"
  "\n" "| Contract | Chain | Address |\n" "| :---- | :---- | :---- |\n"
  "| UniswapWormholeSender | Ethereum | [0xf5F4496219F31CDCBa6130B5402873624585615a](https://etherscan.io/address/0xf5F4496219F31CDCBa6130B5402873624585615a) |\n"
  "| UniswapWormholeReceiver | Avalanche | [0x47eB0Cf11a1626462Da3C830bCDe64c3F582B5a6](https://snowtrace.io/address/0x47eB0Cf11a1626462Da3C830bCDe64c3F582B5a6) |\n"
  "| UniswapWormholeReceiver | MegaETH | [0xa107580F73BD797Bd8b87Ff24e98346D99F93DdB](https://explorer.megaeth.com/address/0xa107580F73BD797Bd8b87Ff24e98346D99F93DdB) |\n"
  "\n"
  "For a detailed discussion of how Wormhole works, please see [this report](https://uniswap.notion.site/Assessment-dac583c6db1240c7b9d294afd7f18035) by the Uniswap Foundation's Bridge Assessment Committee.\n"
  "\n" "### Current Configuration - Soneium and X Layer\n" "\n"
  "On both chains, the UniswapV2Factory's feeToSetter parameter and the v4 PoolManager's owner parameter are configured as the mainnet Timelock's alias address.\n"
  "| Account | Chain | Address |\n" "| :---- | :---- | :---- |\n"
  "| Alias Address | X Layer | [0x2BAD8182C09F50c8318d769245beA52C32Be46CD](https://www.oklink.com/x-layer/evm/address/0x2bad8182c09f50c8318d769245bea52c32be46cd) |\n"
  "| Alias Address | Soneium | [0x2BAD8182C09F50c8318d769245beA52C32Be46CD](https://soneium.blockscout.com/address/0x2BAD8182C09F50c8318d769245beA52C32Be46CD) |\n"
  "\n" "### Proposed Configuration - Soneium and X Layer\n" "\n"
  "This proposal will change those parameters to a CrossChainAccount contract deployed by Uniswap Labs.\n"
  "| Contract | Chain | Address |\n" "| :---- | :---- | :---- |\n"
  "| CrossChainAccount | X Layer | [0x044aAF330d7fD6AE683EEc5c1C1d1fFf5196B6b7](https://www.oklink.com/x-layer/evm/address/0x044aAF330d7fD6AE683EEc5c1C1d1fFf5196B6b7) |\n"
  "| CrossChainAccount | Soneium | [0x044aAF330d7fD6AE683EEc5c1C1d1fFf5196B6b7](https://soneium.blockscout.com/address/0x044aAF330d7fD6AE683EEc5c1C1d1fFf5196B6b7?tab=contract) |\n"
  "\n" "### Onchain Proposal Spec\n" "\n" "**Pre-proposal** (already completed by Uniswap Labs):\n"
  "\n"
  "* Deploy `UniswapWormholeReceiver` on Avalanche C-Chain, configured with the Wormhole Core Bridge address for Avalanche and the address of the existing UniswapWormholeSender.\n"
  "\n"
  "* Deploy `UniswapWormholeReceiver` on MegaETH, configured with the Wormhole Core Bridge address for MegaETH and the address of the existing UniswapWormholeSender.\n"
  "\n" "* Deploy `CrossChainAccount` contracts on Soneium and X Layer\n" "\n"
  "**In this proposal** (executed if the vote passes):\n" "\n" "Execute seven actions:\n" "\n"
  "1. Finalize LayerZero configuration on MegaETH\n" "\n"
  "2. Transfer ownership of the protocol on MegaETH from LayerZero to Wormhole \n" "\n"
  "3. Transfer ownership of the protocol on Avalanche from LayerZero to Wormhole\n" "\n"
  "4. Change v2's `feeToSetter` on X Layer from the alias address to the `CrosschainAccount`\n" "\n"
  "5. Change v4's `owner` on X Layer from the alias address to the `CrosschainAccount`\n" "\n"
  "6. Change v2's `feeToSetter` on Soneium from the alias address to the `CrosschainAccount`\n" "\n"
  "7. Change v4's `owner` on Soneium from the alias address to the `CrosschainAccount`\n" "\n" "\n"
  "\n" "---\n" "\n" "## Next Steps / Timeline\n" "\n" "* **RFC:** Jun 19, 2026\n" "\n"
  "* **Snapshot:** ~1 week after RFC\n" "\n"
  "* **Onchain vote:** Following Snapshot, per standard governance cadence\n" "\n" "---\n" "\n"
  "## Supporting Documents\n" "\n"
  "* [Uniswap Foundation Bridge Assessment Report](https://uniswap.notion.site/Bridge-Assessment-Report-0c8477afadce425abac9c0bd175ca382)\n"
  "\n"
  "* [Uniswap-Wormhole-Bridge GitHub](https://github.com/uniswapfoundation/Uniswap-Wormhole-Bridge)\n"
  "\n"
  "* [LayerZero v1 deprecation announcement](https://layerzero.network/blog/ongoing-security-updates)\n"
  "\n"
  "* [Original Avalanche deployment proposal](https://gov.uniswap.org/t/deploy-uniswap-v3-on-avalanche/20587)\n";
