// SPDX-License-Identifier: MIT
pragma solidity 0.8.29;

string constant DESCRIPTION = "# Protocol Fee Expansion: Robinhood Chain" ""
  "*This proposal is part of the protocol fee rollout, following proposals [#93](https://vote.uniswapfoundation.org/proposals/93), [#94](https://vote.uniswapfoundation.org/proposals/94), [#95](https://vote.uniswapfoundation.org/proposals/95), and [#96](https://vote.uniswapfoundation.org/proposals/96). It uses the expedited governance process [approved](https://gov.uniswap.org/t/unification-proposal/25881#p-57882-protocol-fee-rollout-4) in UNIfication, where fee parameter update proposals can bypass the RFC stage and go directly to a five-day Snapshot followed by an onchain vote.*"
  ""
  "Since protocol fees went live on Ethereum mainnet in late December last year, the rollout has extended to ten additional chains: Arbitrum, Base, OP Mainnet, Worldchain, X Layer, Soneium, Zora, Celo, BNB Chain, and Polygon. The burn system is working as designed, with fees accumulating in TokenJars across chains. From there, searchers claim them in exchange for burning UNI by bridging it back to mainnet and sending it to the burn address."
  ""
  "Uniswap [launched on Robinhood Chain](https://blog.uniswap.org/robinhood-chain-is-live) at the chain's July 1, 2026 mainnet debut, with v2, v3, and v4 all live. As of July 10, the deployments have crossed [$1b of cumulative swap volume](https://x.com/DefiLlama/status/2075608063969485082?s=20). This proposal:"
  "" "- Extends the infrastructure for collecting and burning protocol fees to Robinhood Chain"
  "- Enables v2, v3, and v4 protocol fees on Robinhood Chain" "" "## Implementation Details" ""
  "Fees on Robinhood Chain will be routed to the TokenJar on that chain. UNI burned on Robinhood Chain is bridged back to Ethereum mainnet and sent to the burn address."
  ""
  "Robinhood Chain is an Arbitrum Orbit chain, so this proposal reuses the pattern from the Arbitrum One activation in proposal 94."
  ""
  "**Governance path.** Same as Arbitrum One: cross-chain governance messages are delivered as retryable tickets through Robinhood Chain's Inbox contract on Ethereum and executed on Robinhood Chain by the L2 alias of the governance Timelock. The aliased Timelock already controls both factories and the v4 PoolManager on Robinhood Chain (it is the v2 factory's feeToSetter and the owner of the v3 factory and the PoolManager), so no ownership migration is required."
  ""
  "**Burn path.** The releaser, ArbitrumOrbitResourceFirepit, is the Arbitrum One firepit generalized for Orbit chains. A searcher pays bridged UNI on Robinhood Chain to claim the TokenJar's accumulated fees, and the contract withdraws that UNI to the burn address on mainnet through the canonical gateway. As on Arbitrum One, the withdrawal finalizes on mainnet after Robinhood Chain's challenge period."
  ""
  "The TokenJar, Releaser, V3OpenFeeAdapter, V4FeeAdapter, and V4FeePolicy will be deployed ahead of the onchain votes, with ownership verified against the aliased Timelock. This post will be updated with those addresses when they've been deployed and a link to the repo containing the contracts and deployment scripts once it has been merged."
  ""
  "Implementation details for the v4 fee system are in the [v4 fee activation temp check](https://gov.uniswap.org/t/temp-check-activate-v4-protocol-fees/26162). v2 and v3 protocol fee levels are the same as on all other chains where fees are live, see breakdown [here](https://developers.uniswap.org/docs/protocols/protocol-fee/concepts/fees#fee-split-table)."
  "" "## Proposal Spec" ""
  "If passed, the Robinhood Fee Activation proposal will execute two calls, each creating a retryable ticket in Robinhood Chain's Inbox on Ethereum."
  "" "`RH_INBOX.createRetryableTicket(...) x2`" "" "One call will encode:" ""
  "`V2_FACTORY.setFeeTo(TOKEN_JAR)`" "" "The other will encode:" ""
  "`V3_FACTORY.setOwner(V3_OPEN_FEE_ADAPTER)`" ""
  "Once executed on Robinhood Chain, they set the fee collector of UniswapV2Factory to TokenJar and transfer ownership of UniswapV3Factory to V3OpenFeeAdapter."
  ""
  "Robinhood's v4 activation will be included in the V4 Fee Activation (Part 1) proposal described below. Matching the spec of the [v4 fee activation temp check](https://gov.uniswap.org/t/temp-check-activate-v4-protocol-fees/26162), and delivered through the same retryable ticket path, it will encode:"
  "" "`V4_POOL_MANAGER.setProtocolFeeController(V4_FEE_ADAPTER)`" "" "**RELEVANT ADDRESSES:**" ""
  "| Name | Network | Address | Description |" "| :-- | :-- | :-- | :--|"
  "| V2_FACTORY | Robinhood Chain | [0x8bcEaA40B9AcdfAedF85AdF4FF01F5Ad6517937f](https://robinhoodchain.blockscout.com/address/0x8bcEaA40B9AcdfAedF85AdF4FF01F5Ad6517937f) | Uniswap V2 Factory |"
  "| V3_FACTORY | Robinhood Chain | [0x1f7d7550B1b028f7571E69A784071F0205FD2EfA](https://robinhoodchain.blockscout.com/address/0x1f7d7550B1b028f7571E69A784071F0205FD2EfA) | Uniswap V3 Factory |"
  "| V4_POOL_MANAGER | Robinhood Chain | [0x8366a39cc670b4001a1121b8f6a443a643e40951](https://robinhoodchain.blockscout.com/address/0x8366a39cc670b4001a1121b8f6a443a643e40951) | Uniswap V4 Pool Manager |"
  "| L2_GATEWAY_ROUTER | Robinhood Chain | [0x1E324B9316138CA9a73F960213621AD1aaf01B89](https://robinhoodchain.blockscout.com/address/0x1E324B9316138CA9a73F960213621AD1aaf01B89) | Canonical L2 Gateway Router |"
  "| ALIASED_TIMELOCK | Robinhood Chain | [0x2BAD8182C09F50c8318d769245beA52C32BE46CD](https://robinhoodchain.blockscout.com/address/0x2BAD8182C09F50c8318d769245beA52C32BE46CD) | L2 alias of the governance Timelock |"
  "| RH_INBOX | Ethereum | [0x1A07cc4BD17E0118BdB54D70990D2158AbAD7a2D](https://etherscan.io/address/0x1A07cc4BD17E0118BdB54D70990D2158AbAD7a2D) | Robinhood Chain Delayed Inbox |"
  "| TOKEN_JAR | Robinhood Chain | TBD | Fee Collector |"
  "| V3_OPEN_FEE_ADAPTER | Robinhood Chain | TBD | Uniswap V3 Fee Adapter |"
  "| V4_FEE_ADAPTER | Robinhood Chain | TBD | Uniswap V4 Fee Adapter (protocolFeeController) |"
  "| V4_FEE_POLICY | Robinhood Chain | TBD | Uniswap V4 Fee Policy |"
  "| RELEASER | Robinhood Chain | TBD | ArbitrumOrbitResourceFirepit (searcher burn) |"
  "| UNI | Robinhood Chain | TBD| Bridged UNI |" "" "## Onchain Execution" ""
  "This Snapshot covers v2, v3, and v4 fees on Robinhood Chain, but onchain execution will be split across three proposals. A [separate Snapshot](https://snapshot.box/#/s:uniswapgovernance.eth/proposal/0x3fda3c04fa106ad45173011ef4dfa5db2f14cd35c3c3a7a40f067a44cbadd5f4) to enable v4 fees on the eleven chains where v2/v3 fees are already live concludes this weekend. The v4 activation is the same call on every chain (set the PoolManager's protocolFeeController to the V4FeeAdapter), so it is faster and safer to batch the v4 activations together and keep Robinhood's v2/v3 calls on their own:"
  "" "1. **Robinhood Fee Activation**: the two calls specced above"
  "2. **V4 Fee Activation (Part 1)**: Ethereum, Base, Robinhood, BNB Chain, Arbitrum, Optimism, Polygon"
  "3. **V4 Fee Activation (Part 2)**: Celo, Soneium, X Layer, World Chain, Zora" ""
  "Robinhood Fee Activation and V4 Part 1 will go onchain first, with Part 2 following once a proposer wallet frees up. Robinhood's v4 fees will be enabled through Part 1, contingent on both Snapshots passing."
  "" "## Next Steps / Timeline" "" "- **Snapshot begins:** Jul 10, 2026"
  "- **Snapshot ends:** Jul 15, 2026"
  "*This proposal is part of the protocol fee rollout, following proposals [#93](https://vote.uniswapfoundation.org/proposals/93), [#94](https://vote.uniswapfoundation.org/proposals/94), [#95](https://vote.uniswapfoundation.org/proposals/95), and [#96](https://vote.uniswapfoundation.org/proposals/96). It uses the expedited governance process [approved](https://gov.uniswap.org/t/unification-proposal/25881#p-57882-protocol-fee-rollout-4) in UNIfication, where fee parameter update proposals can bypass the RFC stage and go directly to a five-day Snapshot followed by an onchain vote.*"
  ""
  "Since protocol fees went live on Ethereum mainnet in late December last year, the rollout has extended to ten additional chains: Arbitrum, Base, OP Mainnet, Worldchain, X Layer, Soneium, Zora, Celo, BNB Chain, and Polygon. The burn system is working as designed, with fees accumulating in TokenJars across chains. From there, searchers claim them in exchange for burning UNI by bridging it back to mainnet and sending it to the burn address."
  ""
  "Uniswap [launched on Robinhood Chain](https://blog.uniswap.org/robinhood-chain-is-live) at the chain's July 1, 2026 mainnet debut, with v2, v3, and v4 all live. As of July 10, the deployments have crossed [$1b of cumulative swap volume](https://x.com/DefiLlama/status/2075608063969485082?s=20). This proposal:"
  "" "- Extends the infrastructure for collecting and burning protocol fees to Robinhood Chain"
  "- Enables v2, v3, and v4 protocol fees on Robinhood Chain" "" "## Implementation Details" ""
  "Fees on Robinhood Chain will be routed to the TokenJar on that chain. UNI burned on Robinhood Chain is bridged back to Ethereum mainnet and sent to the burn address."
  ""
  "Robinhood Chain is an Arbitrum Orbit chain, so this proposal reuses the pattern from the Arbitrum One activation in proposal 94."
  ""
  "**Governance path.** Same as Arbitrum One: cross-chain governance messages are delivered as retryable tickets through Robinhood Chain's Inbox contract on Ethereum and executed on Robinhood Chain by the L2 alias of the governance Timelock. The aliased Timelock already controls both factories and the v4 PoolManager on Robinhood Chain (it is the v2 factory's feeToSetter and the owner of the v3 factory and the PoolManager), so no ownership migration is required."
  ""
  "**Burn path.** The releaser, ArbitrumOrbitResourceFirepit, is the Arbitrum One firepit generalized for Orbit chains. A searcher pays bridged UNI on Robinhood Chain to claim the TokenJar's accumulated fees, and the contract withdraws that UNI to the burn address on mainnet through the canonical gateway. As on Arbitrum One, the withdrawal finalizes on mainnet after Robinhood Chain's challenge period."
  ""
  "The TokenJar, Releaser, V3OpenFeeAdapter, V4FeeAdapter, and V4FeePolicy will be deployed ahead of the onchain votes, with ownership verified against the aliased Timelock. This post will be updated with those addresses when they've been deployed and a link to the repo containing the contracts and deployment scripts once it has been merged."
  ""
  "Implementation details for the v4 fee system are in the [v4 fee activation temp check](https://gov.uniswap.org/t/temp-check-activate-v4-protocol-fees/26162). v2 and v3 protocol fee levels are the same as on all other chains where fees are live, see breakdown [here](https://developers.uniswap.org/docs/protocols/protocol-fee/concepts/fees#fee-split-table)."
  "" "## Proposal Spec" ""
  "If passed, the Robinhood Fee Activation proposal will execute two calls, each creating a retryable ticket in Robinhood Chain's Inbox on Ethereum."
  "" "`RH_INBOX.createRetryableTicket(...) x2`" "" "One call will encode:" ""
  "`V2_FACTORY.setFeeTo(TOKEN_JAR)`" "" "The other will encode:" ""
  "`V3_FACTORY.setOwner(V3_OPEN_FEE_ADAPTER)`" ""
  "Once executed on Robinhood Chain, they set the fee collector of UniswapV2Factory to TokenJar and transfer ownership of UniswapV3Factory to V3OpenFeeAdapter."
  ""
  "Robinhood's v4 activation will be included in the V4 Fee Activation (Part 1) proposal described below. Matching the spec of the [v4 fee activation temp check](https://gov.uniswap.org/t/temp-check-activate-v4-protocol-fees/26162), and delivered through the same retryable ticket path, it will encode:"
  "" "`V4_POOL_MANAGER.setProtocolFeeController(V4_FEE_ADAPTER)`" "[9:24 AM]**RELEVANT ADDRESSES:**"
  "" "| Name | Network | Address | Description |" "| :-- | :-- | :-- | :--|"
  "| V2_FACTORY | Robinhood Chain | [0x8bcEaA40B9AcdfAedF85AdF4FF01F5Ad6517937f](https://robinhoodchain.blockscout.com/address/0x8bcEaA40B9AcdfAedF85AdF4FF01F5Ad6517937f) | Uniswap V2 Factory |"
  "| V3_FACTORY | Robinhood Chain | [0x1f7d7550B1b028f7571E69A784071F0205FD2EfA](https://robinhoodchain.blockscout.com/address/0x1f7d7550B1b028f7571E69A784071F0205FD2EfA) | Uniswap V3 Factory |"
  "| V4_POOL_MANAGER | Robinhood Chain | [0x8366a39cc670b4001a1121b8f6a443a643e40951](https://robinhoodchain.blockscout.com/address/0x8366a39cc670b4001a1121b8f6a443a643e40951) | Uniswap V4 Pool Manager |"
  "| L2_GATEWAY_ROUTER | Robinhood Chain | [0x1E324B9316138CA9a73F960213621AD1aaf01B89](https://robinhoodchain.blockscout.com/address/0x1E324B9316138CA9a73F960213621AD1aaf01B89) | Canonical L2 Gateway Router |"
  "| ALIASED_TIMELOCK | Robinhood Chain | [0x2BAD8182C09F50c8318d769245beA52C32BE46CD](https://robinhoodchain.blockscout.com/address/0x2BAD8182C09F50c8318d769245beA52C32BE46CD) | L2 alias of the governance Timelock |"
  "| RH_INBOX | Ethereum | [0x1A07cc4BD17E0118BdB54D70990D2158AbAD7a2D](https://etherscan.io/address/0x1A07cc4BD17E0118BdB54D70990D2158AbAD7a2D) | Robinhood Chain Delayed Inbox |"
  "| TOKEN_JAR | Robinhood Chain | TBD | Fee Collector |"
  "| V3_OPEN_FEE_ADAPTER | Robinhood Chain | TBD | Uniswap V3 Fee Adapter |"
  "| V4_FEE_ADAPTER | Robinhood Chain | TBD | Uniswap V4 Fee Adapter (protocolFeeController) |"
  "| V4_FEE_POLICY | Robinhood Chain | TBD | Uniswap V4 Fee Policy |"
  "| RELEASER | Robinhood Chain | TBD | ArbitrumOrbitResourceFirepit (searcher burn) |"
  "| UNI | Robinhood Chain | TBD| Bridged UNI |" "" "## Onchain Execution" ""
  "This Snapshot covers v2, v3, and v4 fees on Robinhood Chain, but onchain execution will be split across three proposals. A [separate Snapshot](https://snapshot.box/#/s:uniswapgovernance.eth/proposal/0x3fda3c04fa106ad45173011ef4dfa5db2f14cd35c3c3a7a40f067a44cbadd5f4) to enable v4 fees on the eleven chains where v2/v3 fees are already live concludes this weekend. The v4 activation is the same call on every chain (set the PoolManager's protocolFeeController to the V4FeeAdapter), so it is faster and safer to batch the v4 activations together and keep Robinhood's v2/v3 calls on their own:"
  "" "1. **Robinhood Fee Activation**: the two calls specced above"
  "2. **V4 Fee Activation (Part 1)**: Ethereum, Base, Robinhood, BNB Chain, Arbitrum, Optimism, Polygon"
  "3. **V4 Fee Activation (Part 2)**: Celo, Soneium, X Layer, World Chain, Zora" ""
  "Robinhood Fee Activation and V4 Part 1 will go onchain first, with Part 2 following once a proposer wallet frees up. Robinhood's v4 fees will be enabled through Part 1, contingent on both Snapshots passing."
  "" "## Next Steps / Timeline" "" "- **Snapshot begins:** Jul 10, 2026"
  "- **Snapshot ends:** Jul 15, 2026"
  "- **Onchain votes:** Robinhood Fee Activation and V4 Fee Activation (Part 1) following the Snapshots, per standard governance cadence; V4 Fee Activation (Part 2) to follow";
