// SPDX-License-Identifier: MIT
pragma solidity 0.8.29;

string constant DESCRIPTION = "# Protocol Fee Expansion: Robinhood Chain\n"
"\n"
"*This proposal is part of the protocol fee rollout, following proposals [#93](https://vote.uniswapfoundation.org/proposals/93), [#94](https://vote.uniswapfoundation.org/proposals/94), [#95](https://vote.uniswapfoundation.org/proposals/95), and [#96](https://vote.uniswapfoundation.org/proposals/96). It uses the expedited governance process [approved](https://gov.uniswap.org/t/unification-proposal/25881#p-57882-protocol-fee-rollout-4) in UNIfication, where fee parameter update proposals can bypass the RFC stage and go directly to a five-day Snapshot followed by an onchain vote.*\n"
"\n"
"Since protocol fees went live on Ethereum mainnet in late December last year, the rollout has extended to ten additional chains: Arbitrum, Base, OP Mainnet, Worldchain, X Layer, Soneium, Zora, Celo, BNB Chain, and Polygon. The burn system is working as designed, with fees accumulating in TokenJars across chains. From there, searchers claim them in exchange for burning UNI by bridging it back to mainnet and sending it to the burn address.\n"
"\n"
"Uniswap [launched on Robinhood Chain](https://blog.uniswap.org/robinhood-chain-is-live) at the chain's July 1, 2026 mainnet debut, with v2, v3, and v4 all live. As of July 10, the deployments have crossed $6b of cumulative swap volume. This proposal:\n"
"\n"
"- Extends the infrastructure for collecting and burning protocol fees to Robinhood Chain\n"
"- Enables v2, v3, and v4 protocol fees on Robinhood Chain. \n"
"\n"
"Please note that this onchain vote enables v2 and v3 fees specifically, while v4 fees will be activated as a part of a separate proposal covering part 1 of the v4 fee activation.\n"
"\n"
"## Implementation Details\n"
"\n"
"Fees on Robinhood Chain will be routed to the TokenJar on that chain. UNI burned on Robinhood Chain is bridged back to Ethereum mainnet and sent to the burn address.\n"
"\n"
"Robinhood Chain is an Arbitrum Orbit chain, so this proposal reuses the pattern from the Arbitrum One activation in proposal 94.\n"
"\n"
"**Governance path.** Same as Arbitrum One: cross-chain governance messages are delivered as retryable tickets through Robinhood Chain's Inbox contract on Ethereum and executed on Robinhood Chain by the L2 alias of the governance Timelock. The aliased Timelock already controls both factories and the v4 PoolManager on Robinhood Chain (it is the v2 factory's feeToSetter and the owner of the v3 factory and the PoolManager), so no ownership migration is required.\n"
"\n"
"**Burn path.** The releaser, ArbitrumOrbitResourceFirepit, is the Arbitrum One firepit generalized for Orbit chains. A searcher pays bridged UNI on Robinhood Chain to claim the TokenJar's accumulated fees, and the contract withdraws that UNI to the burn address on mainnet through the canonical gateway. As on Arbitrum One, the withdrawal finalizes on mainnet after Robinhood Chain's challenge period.\n"
"\n"
"The TokenJar, Releaser, V3OpenFeeAdapter, V4FeeAdapter, and V4FeePolicy will be deployed ahead of the onchain votes, with ownership verified against the aliased Timelock. This post will be updated with those addresses when they've been deployed and a link to the repo containing the contracts and deployment scripts once it has been merged.\n"
"\n"
"Implementation details for the v4 fee system are in the [v4 fee activation temp check](https://gov.uniswap.org/t/temp-check-activate-v4-protocol-fees/26162). v2 and v3 protocol fee levels are the same as on all other chains where fees are live, see breakdown [here](https://developers.uniswap.org/docs/protocols/protocol-fee/concepts/fees#fee-split-table).\n"
"\n"
"## Proposal Spec\n"
"\n"
"If passed, the Robinhood Fee Activation proposal will execute two calls, each creating a retryable ticket in Robinhood Chain's Inbox on Ethereum.\n"
"\n"
"`RH_INBOX.createRetryableTicket(...) x2`\n"
"\n"
"One call will encode:\n"
"\n"
"`V2_FACTORY.setFeeTo(TOKEN_JAR)`\n"
"\n"
"The other will encode:\n"
"\n"
"`V3_FACTORY.setOwner(V3_OPEN_FEE_ADAPTER)`\n"
"\n"
"Once executed on Robinhood Chain, they set the fee collector of UniswapV2Factory to TokenJar and transfer ownership of UniswapV3Factory to V3OpenFeeAdapter.\n"
"\n"
"Robinhood's v4 activation will be included in the V4 Fee Activation (Part 1) proposal described below. Matching the spec of the [v4 fee activation temp check](https://gov.uniswap.org/t/temp-check-activate-v4-protocol-fees/26162), and delivered through the same retryable ticket path, it will encode:\n"
"\n"
"`V4_POOL_MANAGER.setProtocolFeeController(V4_FEE_ADAPTER)`\n"
"\n"
"## Onchain Execution\n"
"\n"
"This Onchain vote covers v2 and v3 fees on Robinhood Chain. v4 fees on Robinhood Chain have been batched in with part 1 of v4 fee activation, as noted above. \n"
"\n"
"All contracts can be found [here](https://github.com/Uniswap/protocol-fees/), and this post will be updated with addresses and explorer links when they have been deployed.\n"
"\n"
"## Next Steps / Timeline\n"
"\n"
"- **Onchain vote begins:** Jul 19, 2026\n"
"- **Onchain ends:** Jul 26, 2026\n";
