[profile.default]
evm_version = "cancun"
optimizer = true
optimizer_runs = 10_000_000
solc_version = "0.8.29"
verbosity = 3
gas_limit = "9223372036854775807"
no_match_test = "test_fuzz_gas_release_malicious"

additional_compiler_profiles = [
  { name = "wormhole_infra", optimizer_runs = 200 }
]

compilation_restrictions = [
    { paths = "lib/native-token-transfers/evm/src/NttManager/NttManagerNoRateLimiting.sol", optimizer_runs = 200 },
    { paths = "lib/native-token-transfers/evm/src/Transceiver/WormholeTransceiver.sol", optimizer_runs = 200 }
]

fs_permissions = [{ access = "read", path = "./broadcast"}]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
unichain = "${UNICHAIN_RPC_URL}"
base = "${BASE_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
bnb_chain = "${BNB_CHAIN_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
celo = "${CELO_RPC_URL}"

fork_mainnet = "${FORK_MAINNET_RPC_URL}"
fork_bnb_chain = "${FORK_BNB_CHAIN_RPC_URL}"
fork_celo = "${FORK_CELO_RPC_URL}"
fork_polygon = "${FORK_POLYGON_RPC_URL}"

[profile.ci]
fuzz = { runs = 5000 }
invariant = { runs = 1000 }

[profile.coverage]
fuzz = { runs = 100 }
invariant = { runs = 0 }

[profile.lite]
fuzz = { runs = 50 }
invariant = { runs = 10 }
# Speed up compilation and tests during development.
optimizer = false

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 100
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
single_line_statement_blocks = "single"
tab_width = 2
wrap_comments = true

[lint]
exclude_lints = ["mixed-case-variable", "mixed-case-function"]

