// SPDX-License-Identifier: MIT
pragma solidity 0.8.29;

// Why is this in its own file?
//
// So the `forge fmt` can be told to ignore this text. It's cleaner this way but the forge formatter
// cannot be configured to ignore chunks of a file, only the whole file.
string constant PROPOSAL_DESCRIPTION =
"# **[RFC] Protocol Fee Expansion: Three More Chains**\n"
"\n"
"This proposal is part of the protocol fee rollout, following proposals [#92](https://vote.uniswapfoundation.org/proposals/92), [#93](https://vote.uniswapfoundation.org/proposals/93), and [#94](https://vote.uniswapfoundation.org/proposals/94). It uses the expedited governance process [approved](https://gov.uniswap.org/t/unification-proposal/25881#p-57882-protocol-fee-rollout-4) in UNIfication, a one-week RFC period followed directly by an onchain vote.\n"
"\n"
"We propose to enable v2 and v3 protocol fees on BNB Chain and Polygon, and finish their implementation on Celo.\n"
"\n"
"Celo was included in the previous proposal but a cross-chain messaging configuration error prevented those actions from executing. This proposal includes a corrected deployment for Celo that also completes the authority migration to the native OP stack messaging bridge. \n"
"\n"
"## **Background**\n"
"\n"
"Protocol fees went live on Ethereum mainnet in late December 2025 as part of UNIfication. Since then, the rollout has extended to nine additional chains - Arbitrum, Base, OP Mainnet, Soneium, X Layer, Worldchain, and Zora - with TVL and volume holding steady across deployments. The burn system is working as designed: fees accumulate in TokenJars across chains and are converted to UNI burns by searchers, with UNI bridged back to Ethereum mainnet and sent to `0xdead`.\n"
"\n"
"This proposal extends the same infrastructure to BNB Chain and Polygon, and completes Celo's fee activation through its cross-chain governance path.\n"
"\n"
"## **Implementation Details**\n"
"\n"
"### **Fee Infrastructure**\n"
"\n"
"Each chain receives a deployment of three contracts:\n"
"\n"
"- **TokenJar** - an immutable fee sink where protocol fees accumulate. Only the designated releaser can withdraw.  \n"
"- **Chain-specific Releaser** - enables searchers to exchange a fixed UNI amount for accumulated fee tokens. The UNI is bridged back to Ethereum mainnet and burned at `0xdead`.  \n"
"- **V3OpenFeeAdapter** - the tier-based adapter first deployed as part of proposal #94. Protocol fees are set uniformly across all v3 pools sharing the same LP fee tier. Any pool automatically inherits the default fee for its tier; governance can override individual pools.\n"
"\n"
"Releasers on each chain are configured to burn a local version of UNI. On Celo, that is the UNI bridged through the OP-stack native bridge. On BNB and Polygon, we make use of Wormhole's Native Token Transfer (NTT) mechanism for multichain token management. For full details on our implementation of the NTT infrastructure, please read here.\n"
"\n"
"### **Fee Parameters**\n"
"\n"
"Protocol fee levels match those deployed everywhere else:\n"
"\n"
"| Swap Fee Tier | Protocol Take | Effective Protocol Fee |\n"
"| :---- | :---- | :---- |\n"
"| 0.01% | 1/4 of swap fees | ~0.0025% |\n"
"| 0.05% | 1/4 of swap fees | ~0.0125% |\n"
"| 0.30% | 1/6 of swap fees | ~0.05% |\n"
"| 1.00% | 1/6 of swap fees | ~0.167% |\n"
"\n"
"## **Proposal Spec**\n"
"\n"
"This proposal will execute three actions, one each for Celo, BNB Chain, and Polygon. Each action contains multiple inner calls to take appropriate action on each chain. \n"
"\n"
"### **Celo**\n"
"\n"
"This action sets the fee collector of UniswapV2Factory to TokenJar, transfers ownership of UniswapV2Factory and PoolManager to Optimism CrossChainAccount, and transfers ownership of UniswapV3Factory to V3OpenFeeAdapter.\n"
"\n"
"**RELEVANT ADDRESSES:**\n"
"\n"
"| Name | Network | Address | Description |\n"
"| ----- | ----- | ----- | ----- |\n"
"| V2_FACTORY | Celo | 0x114A43DF6C5f54EBB8A9d70Cd1951D3dD68004c7 | Uniswap V2 Factory |\n"
"| V3_FACTORY | Celo | 0xAfE208a311B21f13EF87E33A90049fC17A7acDEc | Uniswap V3 Factory |\n"
"| V4_POOL_MANAGER | Celo | 0x288dc841A52FCA2707c6947B3A777c5E56cd87BC | Uniswap V4 Pool Manager |\n"
"| TOKEN_JAR | Celo | 0x190c22c5085640D1cB60CeC88a4F736Acb59bb6B | Fee Collector |\n"
"| V3_OPEN_FEE_ADAPTER | Celo | 0xB9952C01830306ea2fAAe1505f6539BD260Bfc48 | Uniswap V3 Fee Adapter |\n"
"| UNISWAP_WORMHOLE_MESSAGE_RECEIVER | Celo | 0x0Eb863541278308c3A64F8E908BC646e27BFD071 | Governance Owned Wormhole Receiver |\n"
"| CROSS_CHAIN_ACCOUNT | Celo | 0x044aAF330d7fD6AE683EEc5c1C1d1fFf5196B6b7 | Governance Owned OP Bridge Receiver |\n"
"| WORMHOLE_SENDER | Ethereum | 0xf5F4496219F31CDCBa6130B5402873624585615a | Wormhole Sender |\n"
"\n"
"```\n"
"WORMHOLE_SENDER.sendMessage(targets, values, datas, UNISWAP_WORMHOLE_MESSAGE_RECEIVER, CELO_CHAIN_ID)\n"
"\n"
"encodes:\n"
"V2_FACTORY.setFeeTo(TOKEN_JAR)\n"
"V2_FACTORY.setFeeToSetter(CROSS_CHAIN_ACCOUNT)\n"
"V3_FACTORY.setOwner(V3_OPEN_FEE_ADAPTER)\n"
"V4_POOL_MANAGER.transferOwnership(CROSS_CHAIN_ACCOUNT)\n"
"```\n"
"\n"
"**BNB Chain**  \n"
"This action sets the fee collector of UniswapV2Factory to TokenJar and transfers ownership of UniswapV3Factory to V3OpenFeeAdapter.\n"
"\n"
"**RELEVANT ADDRESSES:**\n"
"\n"
"| Name | Network | Address | Description |\n"
"| ----- | ----- | ----- | ----- |\n"
"| V2_FACTORY | BNB Chain | 0x8909Dc15e40173Ff4699343b6eB8132c65e18eC6 | Uniswap V2 Factory |\n"
"| V3_FACTORY | BNB Chain | 0xdB1d10011AD0Ff90774D0C6Bb92e5C5c8b4461F7 | Uniswap V3 Factory |\n"
"| V4_POOL_MANAGER | BNB Chain | 0x28e2Ea090877bF75740558f6BFB36A5ffeE9e9dF | Uniswap V4 Pool Manager |\n"
"| UNISWAP_WORMHOLE_MESSAGE_RECEIVER | BNB Chain | 0x341c1511141022cf8eE20824Ae0fFA3491F1302b | Governance Owned Wormhole Receiver |\n"
"| WORMHOLE_SENDER | Ethereum | 0xf5F4496219F31CDCBa6130B5402873624585615a | Wormhole Sender |\n"
"\n"
"```\n"
"WORMHOLE_SENDER.sendMessage(targets, values, datas, UNISWAP_WORMHOLE_MESSAGE_RECEIVER, BNB_CHAIN_ID)\n"
"encodes:\n"
"V2_FACTORY.setFeeTo(TOKEN_JAR)\n"
"V3_FACTORY.setOwner(V3_OPEN_FEE_ADAPTER)\n"
"```\n"
"\n"
"### **Polygon**\n"
"\n"
"This action sets the fee collector of UniswapV2Factory to TokenJar and transfers ownership of UniswapV3Factory to V3OpenFeeAdapter.\n"
"\n"
"**RELEVANT ADDRESSES:**\n"
"\n"
"| Name | Network | Address | Description |\n"
"| ----- | ----- | ----- | ----- |\n"
"| V2_FACTORY | Polygon | 0x9e5A52f57b3038F1B8EeE45F28b3C1967e22799C | Uniswap V2 Factory |\n"
"| V3_FACTORY | Polygon | 0x1F98431c8aD98523631AE4a59f267346ea31F984 | Uniswap V3 Factory |\n"
"| V4_POOL_MANAGER | Polygon | 0x67366782805870060151383F4BbFF9daB53e5cD6 | Uniswap V4 Pool Manager |\n"
"| ETHEREUM_PROXY | Polygon | 0x8a1B966aC46F42275860f905dbC75EfBfDC12374 | Governance Owned FxChild Receiver |\n"
"| POLYGON_FX_ROOT | Ethereum | 0xfe5e5D361b2ad62c541bAb87C45a0B9B018389a2 | Polygon's Sender (on Ethereum) |\n"
"\n"
"```\n"
"POLYGON_FX_ROOT.sendMessageToChild(ETHEREUM_PROXY, abi.encode(targets, values, datas))\n"
"encodes:\n"
"V2_FACTORY.setFeeTo(TOKEN_JAR)\n"
"V3_FACTORY.setOwner(V3_OPEN_FEE_ADAPTER)\n"
"```\n"
;
